CELL_SIZE = 112
CELL_BORDER = 7

STATUS_HEIGHT = 140
SCREEN_HEIGHT = 3 * CELL_SIZE - 2 * CELL_BORDER + STATUS_HEIGHT
SCREEN_WIDTH = 3 * CELL_SIZE - 2 * CELL_BORDER
SHAPE_MARGIN = 15
SHAPE_O_THICKNESS = 10
SHARP_O_RADIUS = CELL_SIZE // 2 - SHAPE_MARGIN
SHAPE_X_THICKNESS = 12


button_w = 140
button_h = 36
button_x = (SCREEN_WIDTH - button_w) // 2
button_y = SCREEN_HEIGHT - STATUS_HEIGHT // 2